# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eternityzone

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Docker login to container registry
        uses: docker/login-action@v2
        with:
          registry: mcr.microsoft.com/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F1954ED638564CCABC3312E3054AF3BC }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_F85F3B1F0DCE45469A8CF76667D0730B }}
          

      - name: Build and Push container to registry
        run: |
          docker build -t mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }} .
          docker push mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2506EDC4BE1B4C8FA86793CCBB00DC3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BEAF748CEA444197979F1624AC9AF178 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EFF52C75A10347C9A32B50B1476311F5 }}

      - name: Deploy container to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'eternityzone'
          slot-name: 'Production'
          images: 'mcr.microsoft.com/azure-app-service/windows/parkingpage:${{ github.sha }}'
          
